### ISSUE TITLE
I can't compile the tools :(

### ISSUE THREAD

**Issue by kle0py** [Kriskras99/ferris_dancing#1]
When I try to combine the tools, I get an error (see screenshot below).

![Capture d'écran 2024-01-11 202258](https://github.com/Kriskras99/ferris_dancing/assets/89277176/d6a1b1d5-a260-44dd-8cf2-8c373b7e5544)

**Comment by Kriskras99** [comment]
Sorry about that. I enabled an experimental feature to speedup building (but did not help significantly).
I've removed it in a new commit.
Update your local copy and then the command in your screenshot should work.
Note that if you want add arguments to the command you need to add a --:
`cargo +nightly run --bin xtxtool -- --help`
You can also install the binary in your path with:
`cargo +nightly install --path ubiart_toolkit --bin xtxtool` (assuming you're in the root directory)

P.S. sorry for the late reply, apparently Github doesn't automatically subscribe you to your own repositories.
