### ISSUE TITLE
compile error: could not compile `ubiart_toolkit` (bin "xtxtool") due to 1 previous error

### ISSUE THREAD

**Issue by mophawka** [Kriskras99/ferris_dancing#3]
warning: fields `0` and `1` are never read
  --> ubiart_toolkit\src\secure_fat\types.rs:44:21
   |
44 | pub struct Path<'a>(&'a str, &'a str);
   |            ----     ^^^^^^^  ^^^^^^^
   |            |
   |            fields in this struct
   |
   = note: `#[warn(dead_code)]` on by default
help: consider changing the fields to be of unit type to suppress this warning while preserving the field numbering, or remove the fields
   |
44 | pub struct Path<'a>((), ());
   |                     ~~  ~~

warning: `ubiart_toolkit` (lib) generated 1 warning
error[E0432]: unresolved import `image::ImageOutputFormat`
 --> ubiart_toolkit\src\bin\xtxtool.rs:9:36
  |
9 | use image::{imageops, ImageBuffer, ImageOutputFormat, Rgba};
  |                                    ^^^^^^^^^^^^^^^^^ no `ImageOutputFormat` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `ubiart_toolkit` (bin "xtxtool") due to 1 previous error

not sure you need this but here goes:

rustc --explain E0432
An import was unresolved.

Erroneous code example:

```
use something::Foo; // error: unresolved import `something::Foo`.
```

In Rust 2015, paths in `use` statements are relative to the crate root. To
import items relative to the current and parent modules, use the `self::` and
`super::` prefixes, respectively.

In Rust 2018 or later, paths in `use` statements are relative to the current
module unless they begin with the name of a crate or a literal `crate::`, in
which case they start from the crate root. As in Rust 2015 code, the `self::`
and `super::` prefixes refer to the current and parent modules respectively.

Also verify that you didn't misspell the import name and that the import exists
in the module from where you tried to import it. Example:

```
use self::something::Foo; // Ok.

mod something {
    pub struct Foo;
}
```

If you tried to use a module from an external crate and are using Rust 2015,
you may have missed the `extern crate` declaration (which is usually placed in
the crate root):

```
extern crate core; // Required to use the `core` crate in Rust 2015.

use core::any;
```

Since Rust 2018 the `extern crate` declaration is not required and
you can instead just `use` it:

```
use core::any; // No extern crate required in Rust 2018.

Thanks for any help

**Comment by Kriskras99** [comment]
Should be fixed!
