### ISSUE TITLE
Error compiling sfattool

### ISSUE THREAD

**Issue by mophawka** [Kriskras99/ferris_dancing#4]
warning: fields `0` and `1` are never read
  --> ubiart_toolkit\src\secure_fat\types.rs:44:21
   |
44 | pub struct Path<'a>(&'a str, &'a str);
   |            ----     ^^^^^^^  ^^^^^^^
   |            |
   |            fields in this struct
   |
   = note: `#[warn(dead_code)]` on by default
help: consider changing the fields to be of unit type to suppress this warning while preserving the field numbering, or remove the fields
   |
44 | pub struct Path<'a>((), ());
   |                     ~~  ~~

warning: `ubiart_toolkit` (lib) generated 1 warning
   Compiling ubiart_toolkit v0.1.0 (E:\_ferris_dancing\ubiart_toolkit)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.20s
     Running `E:\_ferris_dancing\target\debug\sfattool.exe --help`
thread 'main' panicked at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\debug_asserts.rs:112:17:
Command ubiart_toolkit: Short option names must be unique for each argument, but '-h' is in use by both 'header' and 'help' (call `cmd.disable_help_flag(true)` to remove the auto-generated `--help`)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `E:\_ferris_dancing\target\debug\sfattool.exe --help` (exit code: 101)

Is there a wiki or tutorial where i can learn to properly use these tools?

TIA

**Comment by Kriskras99** [comment]
That's also fixed! I should really create integration tests for these programs.
All the documentation I have is in the various README.md's. But if you tell me what you want to accomplish then I can help you.
I do recommend building the binaries in release mode (just use ```cargo build --release```), as some of the code can be quite slow in debug mode.
You can also DM me on Discord, my username is the same there.
